// products.js — shared product data for TXBioResearch catalog and detail pages
var PRODUCTS = [
  {
    slug: "5-amino-1mq",
    name: "5-Amino-1MQ",
    packSize: "1 vial, dosage selectable",
    price: 32,
    category: "Research Compound",
    description: "5-Amino-1MQ is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "acetic-acid-water",
    name: "Acetic Acid Water",
    packSize: "1 vial x 10ml",
    price: 7,
    category: "Research Compound",
    description: "Acetic Acid Water is a research compound intended for laboratory research applications.",
    storage: "Store at room temperature, protect from light. Refrigerate after opening per standard lab protocol.",
    purity: "99% Pure",
    form: "Sterile liquid"
  },
  {
    slug: "ahk-cu",
    name: "AHK-CU",
    packSize: "1 vial x 100mg",
    price: 38,
    category: "Research Compound",
    description: "AHK-CU is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "aod9604",
    name: "AOD9604",
    packSize: "1 vial x 10mg",
    price: 89,
    category: "Research Compound",
    description: "AOD9604 is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "ara290-cibinetide",
    name: "ARA290 (Cibinetide)",
    packSize: "1 vial x 10mg",
    price: 38,
    category: "Research Compound",
    description: "ARA290 (Cibinetide) is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "b12",
    name: "B12",
    packSize: "1 vial x 10ml",
    price: 18,
    category: "Research Compound",
    description: "B12 is a research compound intended for laboratory research applications.",
    storage: "Refrigerate at 2-8°C, protect from light.",
    purity: "99% Pure",
    form: "Liquid solution"
  },
  {
    slug: "bac-water",
    name: "Bacteriostatic Water",
    packSize: "1 vial, dosage selectable",
    price: 16,
    category: "Research Compound",
    description: "Bacteriostatic Water is a research compound intended for laboratory research applications.",
    storage: "Store at room temperature, protect from light. Refrigerate after opening per standard lab protocol.",
    purity: "99% Pure",
    form: "Sterile liquid"
  },
  {
    slug: "botulinum-toxin",
    name: "Botulinum toxin",
    packSize: "1 vial x 100iu",
    price: 159,
    category: "Research Compound",
    description: "Botulinum toxin is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "bpc-10mg-tb10mg",
    name: "BPC 10mg+TB10mg",
    packSize: "1 vial x 20mg",
    price: 106,
    category: "Research Compound",
    description: "BPC 10mg+TB10mg is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "bpc-157",
    name: "BPC 157",
    packSize: "1 vial, dosage selectable",
    price: 30,
    category: "Research Compound",
    description: "BPC 157 is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "bpc-15mg-tb15mg",
    name: "BPC 15mg+TB15mg",
    packSize: "1 vial x 30mg",
    price: 139,
    category: "Research Compound",
    description: "BPC 15mg+TB15mg is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "bpc-5mg-tb5mg",
    name: "BPC 5mg+TB5mg",
    packSize: "1 vial x 10mg",
    price: 53,
    category: "Research Compound",
    description: "BPC 5mg+TB5mg is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "cagrilintide",
    name: "Cagrilintide",
    packSize: "1 vial x 10mg",
    price: 121,
    category: "Research Compound",
    description: "Cagrilintide is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "cagrisema-2-5mg-2-5mg",
    name: "Cagrisema (2.5mg+2.5mg)",
    packSize: "1 vial x 5mg",
    price: 46,
    category: "Research Compound",
    description: "Cagrisema (2.5mg+2.5mg) is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "cagrisema-5mg-5mg",
    name: "Cagrisema(5mg+5mg)",
    packSize: "1 vial x 10mg",
    price: 89,
    category: "Research Compound",
    description: "Cagrisema(5mg+5mg) is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "cartalax",
    name: "Cartalax",
    packSize: "1 vial x 20mg",
    price: 61,
    category: "Research Compound",
    description: "Cartalax is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "cerebrolysin",
    name: "cerebrolysin",
    packSize: "1 vial x 60mg",
    price: 35,
    category: "Research Compound",
    description: "cerebrolysin is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "cjc-1295-without-dac-5mg-ipa-5mg",
    name: "CJC 1295(without DAC)5mg+IPA 5mg",
    packSize: "1 vial x 10mg",
    price: 58,
    category: "Research Compound",
    description: "CJC 1295(without DAC)5mg+IPA 5mg is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "cjc-1295-without-dac",
    name: "CJC 1295(without DAC)",
    packSize: "1 vial, dosage selectable",
    price: 40,
    category: "Research Compound",
    description: "CJC 1295(without DAC) is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "cjc1295-with-dac",
    name: "CJC1295 with DAC",
    packSize: "1 vial x 5mg",
    price: 45,
    category: "Research Compound",
    description: "CJC1295 with DAC is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "dihexa",
    name: "Dihexa",
    packSize: "1 vial x 10mg",
    price: 44,
    category: "Research Compound",
    description: "Dihexa is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "dsip",
    name: "DSIP",
    packSize: "1 vial, dosage selectable",
    price: 31,
    category: "Research Compound",
    description: "DSIP is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "epithalon",
    name: "Epithalon",
    packSize: "1 vial x 10mg",
    price: 25,
    category: "Research Compound",
    description: "Epithalon is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "ghk-cu",
    name: "GHK-Cu",
    packSize: "1 vial, dosage selectable",
    price: 55,
    category: "Research Compound",
    description: "GHK-Cu is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "glow-blend",
    name: "GLOW blend",
    packSize: "1 vial x 70mg",
    price: 95,
    category: "Research Compound",
    description: "GLOW blend is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "glutathione",
    name: "Glutathione",
    packSize: "1 vial, dosage selectable",
    price: 37,
    category: "Research Compound",
    description: "Glutathione is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "hcg",
    name: "HCG",
    packSize: "1 vial, dosage selectable",
    price: 42,
    category: "Research Compound",
    description: "HCG is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "humanin",
    name: "Humanin",
    packSize: "1 vial x 10mg",
    price: 146,
    category: "Research Compound",
    description: "Humanin is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "igf-1-lr3",
    name: "IGF-1 LR3",
    packSize: "1 vial x 100mcg",
    price: 27,
    category: "Research Compound",
    description: "IGF-1 LR3 is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "ipamorelin",
    name: "Ipamorelin",
    packSize: "1 vial, dosage selectable",
    price: 29,
    category: "Research Compound",
    description: "Ipamorelin is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "kisspeptin-10",
    name: "Kisspeptin-10",
    packSize: "1 vial x 10mg",
    price: 56,
    category: "Research Compound",
    description: "Kisspeptin-10 is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "klow-blend",
    name: "KLOW blend",
    packSize: "1 vial x 80mg",
    price: 139,
    category: "Research Compound",
    description: "KLOW blend is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "kpv",
    name: "KPV",
    packSize: "1 vial, dosage selectable",
    price: 22,
    category: "Research Compound",
    description: "KPV is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "l-carnitine-600mg",
    name: "L-carnitine 600mg",
    packSize: "1 vial x 10ml",
    price: 24,
    category: "Research Compound",
    description: "L-carnitine 600mg is a research compound intended for laboratory research applications.",
    storage: "Refrigerate at 2-8°C, protect from light.",
    purity: "99% Pure",
    form: "Liquid solution"
  },
  {
    slug: "lemon-bottle",
    name: "Lemon Bottle",
    packSize: "1 vial x 10ml",
    price: 35,
    category: "Research Compound",
    description: "Lemon Bottle is a research compound intended for laboratory research applications.",
    storage: "Refrigerate at 2-8°C, protect from light.",
    purity: "99% Pure",
    form: "Liquid solution"
  },
  {
    slug: "lipo-c-fatblaster",
    name: "Lipo-C (FatBlaster)",
    packSize: "1 vial x 10ml",
    price: 31,
    category: "Research Compound",
    description: "Lipo-C (FatBlaster) is a research compound intended for laboratory research applications.",
    storage: "Refrigerate at 2-8°C, protect from light.",
    purity: "99% Pure",
    form: "Liquid solution"
  },
  {
    slug: "lipo-c-with-b12",
    name: "Lipo-C with B12",
    packSize: "1 vial x 10ml",
    price: 31,
    category: "Research Compound",
    description: "Lipo-C with B12 is a research compound intended for laboratory research applications.",
    storage: "Refrigerate at 2-8°C, protect from light.",
    purity: "99% Pure",
    form: "Liquid solution"
  },
  {
    slug: "lipo-c",
    name: "Lipo-C",
    packSize: "1 vial",
    price: 90,
    category: "Research Compound",
    description: "Lipo-C is a research compound intended for laboratory research applications.",
    storage: "Refrigerate at 2-8°C, protect from light.",
    purity: "99% Pure",
    form: "Liquid solution"
  },
  {
    slug: "ll37",
    name: "LL37",
    packSize: "1 vial x 5mg",
    price: 53,
    category: "Research Compound",
    description: "LL37 is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "melanotan-i",
    name: "Melanotan I",
    packSize: "1 vial x 10mg",
    price: 31,
    category: "Research Compound",
    description: "Melanotan I is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "melanotan-ii",
    name: "Melanotan II",
    packSize: "1 vial x 10mg",
    price: 31,
    category: "Research Compound",
    description: "Melanotan II is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "mots-c-human",
    name: "MOTS-c (Human)",
    packSize: "1 vial, dosage selectable",
    price: 35,
    category: "Research Compound",
    description: "MOTS-c (Human) is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "nad-plus",
    name: "Nad+",
    packSize: "1 vial, dosage selectable",
    price: 24,
    category: "Research Compound",
    description: "Nad+ is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "oxytocin",
    name: "Oxytocin",
    packSize: "1 vial, dosage selectable",
    price: 22,
    category: "Research Compound",
    description: "Oxytocin is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "pinealon",
    name: "pinealon",
    packSize: "1 vial x 10mg",
    price: 38,
    category: "Research Compound",
    description: "pinealon is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "pt141",
    name: "PT141",
    packSize: "1 vial x 10mg",
    price: 37,
    category: "Research Compound",
    description: "PT141 is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "r-3",
    name: "R-3",
    packSize: "1 vial, dosage selectable",
    price: 70,
    category: "Research Compound",
    description: "R-3 is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "retatrutide-20mg-tirzepatide-40mg",
    name: "Retatrutide 20mg + Tirzepatide 40mg",
    packSize: "1 vial x 60mg",
    price: 157,
    category: "Research Compound",
    description: "Retatrutide 20mg + Tirzepatide 40mg is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "retatrutide-5mg-cagrilintide-5mg",
    name: "Retatrutide 5mg+cagrilintide 5mg",
    packSize: "1 vial x 10mg",
    price: 84,
    category: "Research Compound",
    description: "Retatrutide 5mg+cagrilintide 5mg is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "selank",
    name: "Selank",
    packSize: "1 vial x 10mg",
    price: 35,
    category: "Research Compound",
    description: "Selank is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "semaglutide",
    name: "Semaglutide",
    packSize: "1 vial, dosage selectable",
    price: 69,
    category: "Research Compound",
    description: "Semaglutide is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "semax-10mg-selank-10mg",
    name: "Semax 10mg+Selank 10mg",
    packSize: "1 vial x 20mg",
    price: 80,
    category: "Research Compound",
    description: "Semax 10mg+Selank 10mg is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "semax",
    name: "Semax",
    packSize: "1 vial, dosage selectable",
    price: 35,
    category: "Research Compound",
    description: "Semax is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "sermorelin-acetate",
    name: "Sermorelin Acetate",
    packSize: "1 vial, dosage selectable",
    price: 38,
    category: "Research Compound",
    description: "Sermorelin Acetate is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "slu-pp-332-capsule",
    name: "SLU-PP-332 capsule",
    packSize: "1 bottle x 100 capsules, 500mcg each",
    price: 25,
    category: "Research Compound",
    description: "SLU-PP-332 capsule is a research compound intended for laboratory research applications.",
    storage: "Store at room temperature, protect from light and moisture.",
    purity: "99% Pure",
    form: "Capsule"
  },
  {
    slug: "ss-31",
    name: "SS-31",
    packSize: "1 vial, dosage selectable",
    price: 47,
    category: "Research Compound",
    description: "SS-31 is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "sterile-water",
    name: "Sterile water",
    packSize: "1 vial x 10ml",
    price: 4,
    category: "Research Compound",
    description: "Sterile water is a research compound intended for laboratory research applications.",
    storage: "Store at room temperature, protect from light. Refrigerate after opening per standard lab protocol.",
    purity: "99% Pure",
    form: "Sterile liquid"
  },
  {
    slug: "super-human-blend",
    name: "SUPER Human Blend",
    packSize: "1 vial x 10ml",
    price: 35,
    category: "Research Compound",
    description: "SUPER Human Blend is a research compound intended for laboratory research applications.",
    storage: "Refrigerate at 2-8°C, protect from light.",
    purity: "99% Pure",
    form: "Liquid solution"
  },
  {
    slug: "tb500-thymosin-beta-4",
    name: "TB500 Thymosin Beta-4",
    packSize: "1 vial, dosage selectable",
    price: 42,
    category: "Research Compound",
    description: "TB500 Thymosin Beta-4 is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "tesamorelin",
    name: "Tesamorelin",
    packSize: "1 vial, dosage selectable",
    price: 98,
    category: "Research Compound",
    description: "Tesamorelin is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "thymalin-thymulin",
    name: "Thymalin/Thymulin",
    packSize: "1 vial x 10mg",
    price: 40,
    category: "Research Compound",
    description: "Thymalin/Thymulin is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "thymosin-alpha-1",
    name: "Thymosin alpha 1",
    packSize: "1 vial x 10mg",
    price: 89,
    category: "Research Compound",
    description: "Thymosin alpha 1 is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "tirzepatide",
    name: "Tirzepatide",
    packSize: "1 vial, dosage selectable",
    price: 62,
    category: "Research Compound",
    description: "Tirzepatide is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
  {
    slug: "vip",
    name: "VIP",
    packSize: "1 vial, dosage selectable",
    price: 49,
    category: "Research Compound",
    description: "VIP is a research compound intended for laboratory research applications.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted, refrigerate at 2-8°C and use within the timeframe indicated by your lab protocol.",
    purity: "99% Pure",
    form: "Lyophilized powder"
  },
];